version: '3'

services:

  redis:
    container_name: redis
    image: redis
    restart: on-failure
    ports:
    - 6379:6379
    volumes:
    - ./redis-data:/data
    entrypoint: redis-server --appendonly yes
    networks:
    - demo

networks:
  demo:
    driver: bridge
